version: '3'
volumes:
  semaphore-mysql:
    driver: local
services:
  mysql:
    container_name: ansible_mysql
    image: mysql:8.0
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=semaphore
      - MYSQL_USER=USER_CHANGE_ME
      - MYSQL_PASSWORD=CHANGE_ME
    restart: unless-stopped
  semaphore:
    container_name: ansiblesemaphore
    image: semaphoreui/semaphore:v2.8.90
    user: "${UID}:${GID}"
    ports:
      - 3000:3000
    environment:
      - SEMAPHORE_DB_USER=USER_CHANGE_ME
      - SEMAPHORE_DB_PASS=CHANGE_ME
      - SEMAPHORE_DB_HOST=mysql
      - SEMAPHORE_DB_PORT=3306
      - SEMAPHORE_DB_DIALECT=mysql
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=PW_CHANGE_ME
      - SEMAPHORE_ADMIN_NAME=Admin Name
      - SEMAPHORE_ADMIN_EMAIL=CHANGE_ME@EMAIL.COM
      - SEMAPHORE_ADMIN=USER_CHANGE_ME
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=CHANGE_ME
      - ANSIBLE_HOST_KEY_CHECKING=false  # (optional) change to true if you want to enable host key checking
    volumes:
      - ./inventory/:/inventory:ro
      - ./authorized-keys/:/authorized-keys:ro
      - ./config/:/etc/semaphore:rw
    restart: unless-stopped
    depends_on:
      - mysql
